### ISSUE TITLE
Mapping between Connection IDs and Names

### ISSUE THREAD

**Issue by jklaiber** [wemulate/wemulate#54]
**Is your feature request related to a problem? Please describe.**
Yes, in the moment we are using the connection name in order to change entries in the database. This is not optimal anymore because we have to use the `id` in the `api` and `frontend` module. Therefore we should change the behavior in the `cli` module and use the `id` instead of the appropriate connection name. 

**Describe the solution you'd like**
Use the `id` value instead of the `connection_name` in the cli module.

**Additional context**
There are no changes for the enduser. All the changes have an impact on the behavior of the application in the background but noh impact on the cli output or input.

**Comment by severindellsperger** [comment]
I just checked this behavior. Because we use the connection name in the CLI and the connection id in the API, we will always have a mismatch and have to work with these two elements. However, the request of the connection object via id or name seems not to be a problem. Thus, we can work with the id and connection name without a problem. Therefore, I suggest we leave the external API of the wemulate module like it is. IMHO I think we have other things we can implement/improve with a higher priority.

From my side, this issue can be closed because it's not (so) relevant.

**Comment by jklaiber** [comment]
I agree with you. I close this issue for now.
