### ISSUE TITLE
Install Script Module Version Missmatch

### ISSUE THREAD

**Issue by jklaiber** [wemulate/wemulate#59]
**Describe the bug**
The install script does not handle the different module versions correctly.

**Expected behavior**
The install script should always take the same version of all modules in order to be persistent and that every module can work correctly.

**Comment by severindellsperger** [comment]
The problem is that the different components can have different versions available. 
Example wemulate 2.0.1 and frontend 2.0.0.

The question is if there is any need to deliver an install script that allows an easy installation of old components.
I think installing the latest versions of all components should be appropriate.
